Summerland.Web/Controllers/EnquiryFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Summerland.BL;
using System.Net.Mail;
using System.Collections.Specialized;
using System.Configuration;

namespace Summerland.Web.Controllers
{
	public class EnquiryFormController : BaseController
	{
		//
		// GET: /EnquiryForm/
		public ActionResult Index()
		{
			return View(new Enquiry());
		}

		[HttpPost]
		public ActionResult Index(Enquiry model)
		{
			//return Content(str, "text/html");

			// Validate contact info is provided
			if (string.IsNullOrWhiteSpace(model.TelNum) && !StringUtil.IsEmailAddress(model.Email))
			{
				ModelState.AddModelError("ValidationError", new ApplicationException("Please provide Phone number and/or Email"));

				var errorModel = "Please provide Phone number and/or Email";
				var msgHtml = RenderPartialViewToString("_EnquiryFormError", errorModel);

				return Json(new { error = true, message = msgHtml });
			}

			// Set enquiry date
			model.Date = DateTime.Now;

			// Build MailSettings
			var mailSettings = new MailSettings(
				SmtpDeliveryMethod.Network,
				ConfigurationManager.AppSettings["Website-FromAddress"],
				ConfigurationManager.AppSettings["Website-FromName"],
				null,
				0,
				false,
				null);

			// Build template replacements
			var replacements = new ListDictionary();
			replacements.Add("@@Date", model.Date.ToString());
			replacements.Add("@@FirstName", model.FirstName);
			replacements.Add("@@Surname", model.Surname);
			replacements.Add("@@TelNum", model.TelNum);
			replacements.Add("@@Email", model.Email);
			replacements.Add("@@Message", model.Message);

			// Send template email
			Mailer.SendTemplateMail(
				mailSettings,
				ConfigurationManager.AppSettings["Website-ToAddress"],
				ConfigurationManager.AppSettings["Website-ToName"],
				ConfigurationManager.AppSettings["Website-CCAddresses"],
				ConfigurationManager.AppSettings["Website-BCCAddresses"],
				ConfigurationManager.AppSettings["Enquiry-Subject"],
				Server.MapPath("~/Content/EmailTemplates/Enquiry.html"),
				replacements,
				"/Content/EmailTemplates/",
				"/",
				Server.MapPath("~/Content/EmailTemplates/Wrapper.html"),
				true);

			//Mailer.SendMail(
			//	mailSettings,
			//	"anthony@netricity.co.uk",
			//	"Anthony",
			//	null,
			//	null,
			//	"Website Enquiry",
			//	"Details of enquiry",
			//	false);

			return PartialView("_EnquiryFormThanks", model);
		}
	}
}

Summerland.Web/Controllers/FeedbackFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Summerland.BL;
using System.Net.Mail;
using System.Collections.Specialized;
using System.Configuration;

namespace Summerland.Web.Controllers
{
	public class FeedbackFormController : BaseController
	{
		//
		// GET: /FeedbackForm/
		public ActionResult Index()
		{
			return View(new Feedback());
		}

		[HttpPost]
		public ActionResult Index(Feedback model)
		{
			// Validate contact info is provided
			if (string.IsNullOrWhiteSpace(model.TelNum) && !StringUtil.IsEmailAddress(model.Email))
			{
				ModelState.AddModelError("ValidationError", new ApplicationException("Please provide Phone number and/or Email"));

				var errorModel = "Please provide Phone number and/or Email";
				var msgHtml = RenderPartialViewToString("_FeedbackFormError", errorModel);

				return Json(new { error = true, message = msgHtml });
			}

			// Set Feedback date
			model.Date = DateTime.Now;

			// Build MailSettings
			var mailSettings = new MailSettings(
				SmtpDeliveryMethod.Network,
				ConfigurationManager.AppSettings["Website-FromAddress"],
				ConfigurationManager.AppSettings["Website-FromName"],
				null,
				0,
				false,
				null);

			// Build template replacements
			var replacements = new ListDictionary();
			replacements.Add("@@Date", model.Date.ToString());
			replacements.Add("@@FirstName", model.FirstName);
			replacements.Add("@@Surname", model.Surname);
			replacements.Add("@@TelNum", model.TelNum);
			replacements.Add("@@Email", model.Email);
			replacements.Add("@@Rating", model.Rating.GetValueOrDefault().ToString());
			replacements.Add("@@Message", model.Message);

			// Send template email
			Mailer.SendTemplateMail(
				mailSettings,
				ConfigurationManager.AppSettings["Website-ToAddress"],
				ConfigurationManager.AppSettings["Website-ToName"],
				ConfigurationManager.AppSettings["Website-CCAddresses"],
				ConfigurationManager.AppSettings["Website-BCCAddresses"],
				ConfigurationManager.AppSettings["Feedback-Subject"],
				Server.MapPath("~/Content/EmailTemplates/Feedback.html"),
				replacements,
				"/Content/EmailTemplates/",
				"/",
				Server.MapPath("~/Content/EmailTemplates/Wrapper.html"),
				true);

			return PartialView("_FeedbackFormThanks", model);
		}
	}
}

Summerland.Web/Views/Shared/_AvailabilityKey.cshtml
<div class="k-widget k-calendar key">
	<table class="k-content" cellspacing="0">
		<caption>Key</caption>
		<tr>
			<td class="item"><a class="k-link" href="#" title="Indicates an available date"><div class="dt dt-available"><span>29</span></div></a></td>
			<td class="label" title="Indicates an available date">Available</td>

			<td class="item"><a class="k-link" href="#" title="Indicates a booked date"><div class="dt dt-b"><span>29</span></div></a></td>
			<td class="label" title="Indicates a booked date">Booked</td>

			<td class="item"><a class="k-link" href="#" title="Indicates a provisionally booked date"><div class="dt dt-p"><span>29</span></div></a></td>
			<td class="label" title="Indicates a provisionally booked date">Provisional</td>

			<td class="item"><a class="k-link" href="#" title="Indicates a changeover date"><div class="dt dt-b-pm"><span>29</span></div></a></td>
			<td class="label" title="Indicates a changeover date">Changeover</td>
						
			<td class="k-other-month item"><a href="#" title="A date in another month"><div class="dt dt-available"><span>1</span></div></a></td>
			<td class="label" title="A date in another month">Other month</td>
		</tr>
	</table>
</div>

Summerland.Web/Views/Shared/_Copyright.cshtml
<div class="copyright">
	&copy; Copyright @DateTime.Now.Year.ToString() <a href="http://www.netricity.co.uk/" title="Independant web developer Manchester - Netricity Ltd" target="_blank">Netricity Ltd</a>
</div>

Summerland.Web/Views/Shared/_DefaultSidebar.cshtml
<img src="~/Content/Images/Sidebar/pool-2.jpg" title="Summerland pool" />

<img src="~/Content/Images/Sidebar/pool-4.jpg" title="Summerland pool" />

<img src="~/Content/Images/Sidebar/Livingroom-4.jpg" title="The apartment living room" />

<img src="~/Content/Images/Sidebar/Bedroom-1.jpg" title="The apartment bedroom" />

<img src="~/Content/Images/Sidebar/Balcony-towards-El-Tiede-1.jpg" title="Apartment balcony view towards El Tiede volcano" />

Summerland.Web/Views/Shared/_EnquiryForm.cshtml
@model Summerland.BL.Enquiry

@*@{
	string _id = ViewData.TemplateInfo.HtmlFieldPrefix;
}*@

@*@{
	Html.EnableClientValidation();
}*@

<div class="enquiry-form">
	@*@using (Ajax.BeginForm("Index", "EnquiryForm", null, new AjaxOptions { UpdateTargetId = "result" }, new { id = _id }))*@
	@using (Ajax.BeginForm("Index", "EnquiryForm", null, new AjaxOptions { UpdateTargetId = "result" }, new { id = ViewData["id"] }))
 {
		<fieldset class="fieldset">
			<legend>Enquiry form</legend>

			<div class="editor-label">
				@Html.LabelFor(model => model.FirstName)
			</div>
			@Html.EditorFor(m => m.FirstName)
			@Html.ValidationMessageFor(m => m.FirstName)

			<div class="spacer-v10"></div>

			<div class="editor-label">
				@Html.LabelFor(model => model.Surname)
			</div>
			@Html.EditorFor(m => m.Surname)
			@Html.ValidationMessageFor(m => m.Surname)

			<div class="spacer-v10"></div>

			<div class="editor-label">
				@Html.LabelFor(model => model.TelNum)
			</div>
			@Html.EditorFor(m => m.TelNum)
			@Html.ValidationMessageFor(m => m.TelNum)

			<div class="spacer-v10"></div>

			<div class="editor-label">
				@Html.LabelFor(model => model.Email)
			</div>
			@Html.EditorFor(m => m.Email)
			@Html.ValidationMessageFor(m => m.Email)

			<div class="spacer-v10"></div>

			<div class="editor-label">
				@Html.LabelFor(model => model.Message)
			</div>
			@Html.EditorFor(m => m.Message, new { Rows = 4 })
			@Html.ValidationMessageFor(m => m.Message)

			<div class="spacer-v10"></div>

			<div class="buttons">
				<input type="submit" value="Submit enquiry" title="Submit your enquiry" class="btn btn-primary" />
			</div>
		</fieldset>
	 
		<div class="success">
			<div class="alert alert-success">
				<p class="float-l">
					<span class="icon-tick"></span>
				</p>

				<div class="float-l msg"></div>
			</div>
		</div>

		<div class="error">
			<div class="alert alert-error">
				<p class="float-l">
					<span class="icon-cross"></span>
				</p>

				<div class="float-l msg"></div>
			</div>
		</div>
 }
</div>

<script type="text/javascript">
	$(function () {
		var $fieldset = $('#@ViewData["id"] .fieldset');
		var $success = $('#@ViewData["id"] .success');
		var $successMsg = $('#@ViewData["id"] .success .msg');

		var $error = $('#@ViewData["id"] .error');
		var $errorMsg = $('#@ViewData["id"] .error .msg');

		$success.hide();
		$error.hide();

		//$('form').submit(function () {
		$('#@ViewData["id"]').submit(function () {
			if ($(this).valid()) {

				$success.hide();
				$error.hide();

				$.ajax({
					url: this.action,
					type: this.method,
					data: $(this).serialize(),
					success: function (result) {
						if (result.error === true) {
							$error.show();
							$errorMsg.html(result.message);
						}
						else {
							$fieldset.hide();
							$success.show();
							$successMsg.html(result);
						}
					},
					error: function (result) {
						$error.show();
						$errorMsg.html(result);
					}
				});
			}

			return false;
		});
	});
</script>

Summerland.Web/Views/Shared/_EnquiryFormThanks.cshtml
@model Summerland.BL.Enquiry

<p>
	Thank you for your enquiry, @Model.FirstName.
</p>
<p>
	We'll be in touch as soon as possible!
</p>

Summerland.Web/Views/Shared/_FeedbackForm.cshtml
@model Summerland.BL.Feedback

<div class="feedback-form">
	@using (Ajax.BeginForm("Index", "FeedbackForm", null, new AjaxOptions { UpdateTargetId = "result" }, new { id = ViewData["id"] }))
 {
		<fieldset class="fieldset">
			<legend>Feedback form</legend>

			<div class="editor-label">
				@Html.LabelFor(model => model.FirstName)
			</div>
			@Html.EditorFor(m => m.FirstName)
			@Html.ValidationMessageFor(m => m.FirstName)

			<div class="spacer-v10"></div>

			<div class="editor-label">
				@Html.LabelFor(model => model.Surname)
			</div>
			@Html.EditorFor(m => m.Surname)
			@Html.ValidationMessageFor(m => m.Surname)

			<div class="spacer-v10"></div>

			<div class="editor-label">
				@Html.LabelFor(model => model.TelNum)
			</div>
			@Html.EditorFor(m => m.TelNum)
			@Html.ValidationMessageFor(m => m.TelNum)

			<div class="spacer-v10"></div>

			<div class="editor-label">
				@Html.LabelFor(model => model.Email)
			</div>
			@Html.EditorFor(m => m.Email)
			@Html.ValidationMessageFor(m => m.Email)

			<div class="spacer-v10"></div>

			<div class="editor-label">
				@Html.LabelFor(model => model.Rating)
			</div>
			@Html.EditorFor(m => m.Rating, new { Rows = 4 })
			@Html.ValidationMessageFor(m => m.Rating)

			<div class="spacer-v10"></div>

			<div class="editor-label">
				@Html.LabelFor(model => model.Message)
			</div>
			@Html.EditorFor(m => m.Message, new { Rows = 4 })
			@Html.ValidationMessageFor(m => m.Message)

			<div class="spacer-v10"></div>

			<div class="buttons">
				<input type="submit" value="Submit feedback" title="Submit your feedback" class="btn btn-primary" />
			</div>
		</fieldset>
	 
		<div class="success">
			<div class="alert alert-success">
				<p class="float-l">
					<span class="icon-tick"></span>
				</p>

				<div class="float-l msg"></div>
			</div>
		</div>

		<div class="error">
			<div class="alert alert-error">
				<p class="float-l">
					<span class="icon-cross"></span>
				</p>

				<div class="float-l msg"></div>
			</div>
		</div>
 }
</div>

<script type="text/javascript">
	$(function () {
		var $fieldset = $('#@ViewData["id"] .fieldset');
		var $success = $('#@ViewData["id"] .success');
		var $successMsg = $('#@ViewData["id"] .success .msg');

		var $error = $('#@ViewData["id"] .error');
		var $errorMsg = $('#@ViewData["id"] .error .msg');

		$success.hide();
		$error.hide();

		//$('form').submit(function () {
		$('#@ViewData["id"]').submit(function () {
			if ($(this).valid()) {

				$success.hide();
				$error.hide();

				$.ajax({
					url: this.action,
					type: this.method,
					data: $(this).serialize(),
					success: function (result) {
						if (result.error === true) {
							$error.show();
							$errorMsg.html(result.message);
						}
						else {
							$fieldset.hide();
							$success.show();
							$successMsg.html(result);
						}
					},
					error: function (result) {
						$error.show();
						$errorMsg.html(result);
					}
				});
			}

			return false;
		});
	});
</script>

Summerland.Web/Views/Shared/_FeedbackFormError.cshtml
<p>
	@Model
</p>

Summerland.Web/Views/Shared/_FeedbackFormThanks.cshtml
@model Summerland.BL.Enquiry

<p>
	Thank you for your feedback, @Model.FirstName.
</p>
<p>
	We will place it on this website as soon as possible!
</p>

Summerland.Web/Views/Shared/_Footer.cshtml
<div id="footer">
	<ul id="footer-nav">
		<li class="item">
			&copy; Copyright @DateTime.Now.Year.ToString() <a href="http://www.netricity.co.uk/" title="Independant contract web developer Manchester - Netricity Ltd" target="_blank">Netricity Ltd</a>
		</li>
		<li class="sep">&nbsp;</li>
		<li class="item">
			Further details available on <a href="http://www.holidaylettings.co.uk/rentals/los-cristianos/360113" target="_blank" title="HolidayLettings.co.uk">HolidayLettings.co.uk</a>
		</li>
	</ul>
</div>

Summerland.Web/Views/Shared/_GoogleTrackPageView.cshtml
@if (Request.Url.Host == "localhost" || string.IsNullOrWhiteSpace(Request.QueryString["notrack"]))
{
	<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-38875431-1']);
		_gaq.push(['_trackPageview']);

		(function () {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
	</script>
}

Summerland.Web/Views/Shared/_KendoCulture.cshtml
@{
	var culture = System.Threading.Thread.CurrentThread.CurrentCulture.ToString();
}

<script src="@Url.Content("~/Scripts/kendo.culture." + culture + ".min.js")"></script>

@* Set the current culture *@

<script>
	kendo.culture("@culture");
</script>

Summerland.Web/Views/Shared/_Layout2ColWideLeft.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title>@if (!string.IsNullOrWhiteSpace(ViewBag.Title))
		  {
		@ViewBag.Title}
		  else
		  {
		@:Summarland Apartments
		}</title>

	<meta name="description" content="Holiday apartment for rent in Los Cristianos, Tenerife" />

	@*@Scripts.Render("/bundles/modernizr")*@

	<link rel="stylesheet" href="/Content/kendo.common.min.css">
	<link rel="stylesheet" href="/Content/kendo.default.min.css">
	<link rel="stylesheet" href="/Content/normalize.css" />
	<link rel="stylesheet" href="/Content/themes/summerland/Site.css" />
	<link rel="stylesheet" href="/Content/kendo.custom.css" />

	<script src="/Scripts/jquery.min.js"></script>
	<script src="/Scripts/jquery.unobtrusive-ajax.min.js"></script>
	<script src="/Scripts/jquery.validate.min.js"></script>
	<script src="/Scripts/jquery.validate.unobtrusive.js"></script>
	<script src="/Scripts/kendo.web.min.js"></script>
	<script src="/Scripts/kendo.aspnetmvc.min.js"></script>
	<script src="/Scripts/console.min.js"></script>
	<script src="/Scripts/prettify.min.js"></script>
	<script src="/Scripts/Summerland.js"></script>
	
	<!--[if lte IE 8]>
	<script src="/Scripts/html5shiv.js"></script>
	<![endif]-->

	@Html.Partial("_KendoCulture")

	<meta name="google-site-verification" content="DW4wxjY1D8QKv7-mgQVZTp741VO7pp6RtOT85Yabx0M" />

	<meta name="msvalidate.01" content="21BCB5F01CA713DA43769AB366266252" />
</head>
<body class="orange-bkgd">

	<div class="central-cont">
		<div id="outer-container" class="white-bkgd">
			@Html.Partial("_Header")

			<div id="view-content-col-wide-left" class="float-l generic-content">
				@RenderBody()
			</div>

			<div id="sidebar-col" class="float-r generic-content">
				@if (IsSectionDefined("sidebar"))
				{
				// Render current View's own sidebar
					@RenderSection("sidebar")
				 }
				 else
				 {
				 // Render default sidebar
					@Html.Partial("_DefaultSidebar")
			}
			</div>

		</div>

		@Html.Partial("_footer")

	</div>

	@Html.Partial("_GoogleTrackPageView")

</body>
</html>

Summerland.Web/Views/Shared/_LayoutFullWidth.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title>@if (!string.IsNullOrWhiteSpace(ViewBag.Title))
		  {
		@ViewBag.Title}
		  else
		  {
		@:Summarland Apartments
		}</title>

	<meta name="description" content="Holiday apartment to let in Los Cristianos, Tenerife" />

	@*@Scripts.Render("~/bundles/modernizr")*@

	<link rel="stylesheet" href="~/Content/kendo.common.min.css">
	<link rel="stylesheet" href="~/Content/kendo.default.min.css">
	<link rel="stylesheet" href="~/Content/normalize.css" />
	<link rel="stylesheet" href="~/Content/themes/summerland/Site.css" />
	<link rel="stylesheet" href="~/Content/kendo.custom.css" />

	<script src="/Scripts/jquery.min.js"></script>
	<script src="/Scripts/jquery.unobtrusive-ajax.min.js"></script>
	<script src="/Scripts/jquery.validate.min.js"></script>
	<script src="/Scripts/jquery.validate.unobtrusive.js"></script>
	<script src="/Scripts/kendo.web.min.js"></script>
	<script src="/Scripts/kendo.aspnetmvc.min.js"></script>
	<script src="/Scripts/console.min.js"></script>
	<script src="/Scripts/prettify.min.js"></script>
	<script src="/Scripts/Summerland.js"></script>
	
	<!--[if lte IE 8]>
	<script src="/Scripts/html5shiv.js"></script>
	<![endif]-->

	@Html.Partial("_KendoCulture")

	<meta name="google-site-verification" content="DW4wxjY1D8QKv7-mgQVZTp741VO7pp6RtOT85Yabx0M" />
</head>
<body class="orange-bkgd">

	<div class="central-cont">
		<div id="outer-container" class="white-bkgd">
			@Html.Partial("_Header")

			<div id="view-content-col-full-width" class="float-l generic-content">
				@RenderBody()
			</div>
			
		</div>

		@Html.Partial("_footer")

	</div>

	@Html.Partial("_GoogleTrackPageView")

</body>
</html>

Summerland.Web/Views/Shared/_PriceList.cshtml
@model Summerland.BL.ViewModels.PriceList

<p>
	Prices based on 2 sharing.
</p>

<p>
	@Model.PricePartyOfTwoPounds.ToString("C0") / &euro;@Model.PricePartyOfTwoEuros.ToString("0") per week for 2 guests.
</p>

<p>
	Additional guests &pound;20 / &euro;24, maximum 4 guests.
</p>

<p>
	Additional weeks @Html.ActionLink("please enquire", "contact-us", "more-info", null, new { title = "enquire about additional weeks" }),
</p>

<p>
	Availability from May to October only, no winter availability.
</p>