Summerland.Web/Controllers/AvailabilityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Summerland.Web.Controllers
{
	public class AvailabilityController : BaseController
	{
		/// <summary>
		/// GET: /Availability/
		/// </summary>
		public ActionResult Index()
		{
			// Return view for current year
			var year = DateTime.Now.Year.ToString();
			return View(year);
		}

		/// <summary>
		/// GET: /Availability/2013
		/// </summary>
		[ActionName("2013")]
		public ActionResult Y2013()
		{
			return View();
		}

		/// <summary>
		/// GET: /Availability/2014
		/// </summary>
		[ActionName("2014")]
		public ActionResult Y2014()
		{
			return View();
		}

		/// <summary>
		/// GET: /Availability/2015
		/// </summary>
		[ActionName("2015")]
		public ActionResult Y2015()
		{
			return View();
		}

		/// <summary>
		/// GET: /Availability/2016
		/// </summary>
		[ActionName("2016")]
		public ActionResult Y2016()
		{
			return View();
		}

		/// <summary>
		/// GET: /Availability/2017
		/// </summary>
		[ActionName("2017")]
		public ActionResult Y2017()
		{
			return View();
		}

      /// <summary>
      /// GET: /Availability/2018
      /// </summary>
      [ActionName("2018")]
      public ActionResult Y2018()
      {
         return View();
      }
   }
}

Summerland.Web/Views/Availability/2013.cshtml
@{
	Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
	ViewBag.Title = "2013 Availability - holiday rental apartment in Los Cristianos, Tenerife, Canary Islands";
}

<h1>2013 availability at holiday rental apartment</h1>

<p>
	Check 2013 availability at our holiday rental apartment in Los Cristianos, Tenerife.
</p>

<p>
	<a href="@Url.Action("2014", "Availability")" title="Check 2014 availability at our holiday rental apartment in Los Cristianos, Tenerife.">View 2014 availability</a>.

	<span class="pad-right-30">&nbsp;</span>

	<a href="@Url.Action("2015", "Availability")" title="Check 2015 availability at our holiday rental apartment in Los Cristianos, Tenerife.">View 2015 availability</a>.
</p>

<p>
	@Html.Partial("_AvailabilityKey")
</p>

@(Html.Kendo().Calendar()
		  .Name("calendar201301")
		  .Value(new DateTime(2013, 1, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201302")
		  .Value(new DateTime(2013, 2, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201303")
		  .Value(new DateTime(2013, 3, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201304")
		  .Value(new DateTime(2013, 4, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<div class="spacer-v20"></div>

@(Html.Kendo().Calendar()
		  .Name("calendar201305")
		  .Value(new DateTime(2013, 5, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar202306")
		  .Value(new DateTime(2013, 6, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201307")
		  .Value(new DateTime(2013, 7, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201308")
		  .Value(new DateTime(2013, 8, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<div class="spacer-v20"></div>

@(Html.Kendo().Calendar()
		  .Name("calendar202309")
		  .Value(new DateTime(2013, 9, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201310")
		  .Value(new DateTime(2013, 10, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201311")
		  .Value(new DateTime(2013, 11, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201312")
		  .Value(new DateTime(2013, 12, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<script type="text/javascript" src="~/Scripts/Summerland.js"></script>

Summerland.Web/Views/Availability/2014.cshtml
@{
	Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
	ViewBag.Title = "2014 Availability - holiday rental apartment in Los Cristianos, Tenerife, Canary Islands";
}

<h1>2014 availability at holiday rental apartment</h1>

<p>
	Check 2014 availability at our holiday rental apartment in Los Cristianos, Tenerife.
</p>

<p>
	<a href="@Url.Action("2013", "Availability")" title="Check 2013 availability at our holiday rental apartment in Los Cristianos, Tenerife.">View 2013 availability</a>.
	
	<span class="pad-right-30">&nbsp;</span>

	<a href="@Url.Action("2015", "Availability")" title="Check 2015 availability at our holiday rental apartment in Los Cristianos, Tenerife.">View 2015 availability</a>.
</p>

<p>
	@Html.Partial("_AvailabilityKey")
</p>

@(Html.Kendo().Calendar()
		  .Name("calendar201401")
		  .Value(new DateTime(2014, 1, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201402")
		  .Value(new DateTime(2014, 2, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201403")
		  .Value(new DateTime(2014, 3, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201404")
		  .Value(new DateTime(2014, 4, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<div class="spacer-v20"></div>

@(Html.Kendo().Calendar()
		  .Name("calendar201405")
		  .Value(new DateTime(2014, 5, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar202306")
		  .Value(new DateTime(2014, 6, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201407")
		  .Value(new DateTime(2014, 7, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201408")
		  .Value(new DateTime(2014, 8, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<div class="spacer-v20"></div>

@(Html.Kendo().Calendar()
		  .Name("calendar202309")
		  .Value(new DateTime(2014, 9, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201410")
		  .Value(new DateTime(2014, 10, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201411")
		  .Value(new DateTime(2014, 11, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201412")
		  .Value(new DateTime(2014, 12, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<script type="text/javascript" src="~/Scripts/Summerland.js"></script>

Summerland.Web/Views/Availability/2015.cshtml
@{
	Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
	ViewBag.Title = "2015 Availability - holiday rental apartment in Los Cristianos, Tenerife, Canary Islands";
}

<h1>2015 availability at holiday rental apartment</h1>

<p>
	Check 2015 availability at our holiday rental apartment in Los Cristianos, Tenerife.
</p>

<p>
	<a href="@Url.Action("2016", "Availability")" title="Check 2016 availability at our holiday rental apartment in Los Cristianos, Tenerife.">View 2016 availability</a>.

	<span class="pad-right-30">&nbsp;</span>

	<a href="@Url.Action("2017", "Availability")" title="Check 2017 availability at our holiday rental apartment in Los Cristianos, Tenerife.">View 2017 availability</a>.
</p>

<p>
	@Html.Partial("_AvailabilityKey")
</p>

@(Html.Kendo().Calendar()
		  .Name("calendar201501")
		  .Value(new DateTime(2015, 1, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201502")
		  .Value(new DateTime(2015, 2, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201503")
		  .Value(new DateTime(2015, 3, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201504")
		  .Value(new DateTime(2015, 4, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<div class="spacer-v20"></div>

@(Html.Kendo().Calendar()
		  .Name("calendar201505")
		  .Value(new DateTime(2015, 5, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar202306")
		  .Value(new DateTime(2015, 6, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201507")
		  .Value(new DateTime(2015, 7, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201508")
		  .Value(new DateTime(2015, 8, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<div class="spacer-v20"></div>

@(Html.Kendo().Calendar()
		  .Name("calendar202309")
		  .Value(new DateTime(2015, 9, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201510")
		  .Value(new DateTime(2015, 10, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201511")
		  .Value(new DateTime(2015, 11, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201512")
		  .Value(new DateTime(2015, 12, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<script type="text/javascript" src="~/Scripts/Summerland.js"></script>

Summerland.Web/Views/Availability/2016.cshtml
@{
	Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
	ViewBag.Title = "2016 Availability - holiday rental apartment in Los Cristianos, Tenerife, Canary Islands";
}

<h1>2016 availability at holiday rental apartment</h1>

<p>
	Check 2016 availability at our holiday rental apartment in Los Cristianos, Tenerife.
</p>

<p>
	<a href="@Url.Action("2017", "Availability")" title="Check 2017 availability at our holiday rental apartment in Los Cristianos, Tenerife.">View 2017 availability</a>.

	<span class="pad-right-30">&nbsp;</span>

	<a href="@Url.Action("2018", "Availability")" title="Check 2018 availability at our holiday rental apartment in Los Cristianos, Tenerife.">View 2018 availability</a>.
</p>

<p>
	@Html.Partial("_AvailabilityKey")
</p>

@(Html.Kendo().Calendar()
		  .Name("calendar201601")
		  .Value(new DateTime(2016, 1, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201602")
		  .Value(new DateTime(2016, 2, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201603")
		  .Value(new DateTime(2016, 3, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201604")
		  .Value(new DateTime(2016, 4, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<div class="spacer-v20"></div>

@(Html.Kendo().Calendar()
		  .Name("calendar201605")
		  .Value(new DateTime(2016, 5, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201606")
		  .Value(new DateTime(2016, 6, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201607")
		  .Value(new DateTime(2016, 7, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201608")
		  .Value(new DateTime(2016, 8, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<div class="spacer-v20"></div>

@(Html.Kendo().Calendar()
		  .Name("calendar201609")
		  .Value(new DateTime(2016, 9, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201610")
		  .Value(new DateTime(2016, 10, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201611")
		  .Value(new DateTime(2016, 11, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201612")
		  .Value(new DateTime(2016, 12, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<script type="text/javascript" src="~/Scripts/Summerland.js"></script>

Summerland.Web/Views/Availability/2017.cshtml
@{
	Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
	ViewBag.Title = "2017 Availability - holiday rental apartment in Los Cristianos, Tenerife, Canary Islands";
}

<h1>2017 availability at holiday rental apartment</h1>

<p>
	Check 2017 availability at our holiday rental apartment in Los Cristianos, Tenerife.
</p>

<p>
	<a href="@Url.Action("2015", "Availability")" title="Check 2015 availability at our holiday rental apartment in Los Cristianos, Tenerife.">View 2015 availability</a>.

	<span class="pad-right-30">&nbsp;</span>

	<a href="@Url.Action("2016", "Availability")" title="Check 2016 availability at our holiday rental apartment in Los Cristianos, Tenerife.">View 2016 availability</a>.
</p>

<p>
	@Html.Partial("_AvailabilityKey")
</p>

@(Html.Kendo().Calendar()
		  .Name("calendar201701")
		  .Value(new DateTime(2017, 1, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201702")
		  .Value(new DateTime(2017, 2, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201703")
		  .Value(new DateTime(2017, 3, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201704")
		  .Value(new DateTime(2017, 4, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<div class="spacer-v20"></div>

@(Html.Kendo().Calendar()
		  .Name("calendar201705")
		  .Value(new DateTime(2017, 5, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201706")
		  .Value(new DateTime(2017, 6, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201707")
		  .Value(new DateTime(2017, 7, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201708")
		  .Value(new DateTime(2017, 8, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<div class="spacer-v20"></div>

@(Html.Kendo().Calendar()
		  .Name("calendar201709")
		  .Value(new DateTime(2017, 9, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201710")
		  .Value(new DateTime(2017, 10, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201711")
		  .Value(new DateTime(2017, 11, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201712")
		  .Value(new DateTime(2017, 12, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<script type="text/javascript" src="~/Scripts/Summerland.js"></script>

Summerland.Web/Views/Availability/2018.cshtml
@{
	Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
	ViewBag.Title = "2018 Availability - holiday rental apartment in Los Cristianos, Tenerife, Canary Islands";
}

<h1>2018 availability at holiday rental apartment</h1>

<p>
	Check 2018 availability at our holiday rental apartment in Los Cristianos, Tenerife.
</p>

<p>
	<a href="@Url.Action("2016", "Availability")" title="Check 2016 availability at our holiday rental apartment in Los Cristianos, Tenerife.">View 2016 availability</a>.

	<span class="pad-right-30">&nbsp;</span>

	<a href="@Url.Action("2017", "Availability")" title="Check 2017 availability at our holiday rental apartment in Los Cristianos, Tenerife.">View 2017 availability</a>.
</p>

<p>
	@Html.Partial("_AvailabilityKey")
</p>

@(Html.Kendo().Calendar()
		  .Name("calendar201801")
		  .Value(new DateTime(2018, 1, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201802")
		  .Value(new DateTime(2018, 2, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201803")
		  .Value(new DateTime(2018, 3, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201804")
		  .Value(new DateTime(2018, 4, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<div class="spacer-v20"></div>

@(Html.Kendo().Calendar()
		  .Name("calendar201805")
		  .Value(new DateTime(2018, 5, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201806")
		  .Value(new DateTime(2018, 6, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201807")
		  .Value(new DateTime(2018, 7, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201808")
		  .Value(new DateTime(2018, 8, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<div class="spacer-v20"></div>

@(Html.Kendo().Calendar()
		  .Name("calendar201809")
		  .Value(new DateTime(2018, 9, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201810")
		  .Value(new DateTime(2018, 10, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201811")
		  .Value(new DateTime(2018, 11, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<span class="spacer-h20"></span>

@(Html.Kendo().Calendar()
		  .Name("calendar201812")
		  .Value(new DateTime(2018, 12, 1))
		  .Footer(" ")
		  .MonthTemplate(@"#= BuildDateMarker(data) #")
)

<script type="text/javascript" src="~/Scripts/Summerland.js"></script>

Summerland.Web/Views/Availability/Index.cshtml
@{
	ViewBag.Title = "Availability - Holiday apartment for rent in Los Cristianos, Tenerife, Canary Islands";
}

<h1>Availability</h1>

<ul class="availability-years">
	@*<li>
		<a href="@Url.Action("2013", "Availability")" title="View 2013 availability at Summerland, Tenerife">2013 availability</a>
	</li>
	<li>
		<a href="@Url.Action("2014", "Availability")" title="View 2014 availability at Summerland, Tenerife">2014 availability</a>
	</li>*@
	<li>
		<a href="@Url.Action("2015", "Availability")" title="View 2015 availability at Summerland, Tenerife">2015 availability</a>
	</li>
	<li>
		<a href="@Url.Action("2016", "Availability")" title="View 2016 availability at Summerland, Tenerife">2016 availability</a>
	</li>
	<li>
		<a href="@Url.Action("2017", "Availability")" title="View 2017 availability at Summerland, Tenerife">2017 availability</a>
	</li>
</ul>